// clients/vue-reviews/src/primitives/QnAurora.vue
<!--
 * <QnAurora /> — Vue 3 wrapper around the <qn-aurora> custom
 * element. Props mirror the underlying attributes one-for-one.
 *
 * Events:
 *   @aurora-click  — fires with the aurora detail object
 *
 * Usage:
 *   <QnAurora :rating="4.5" :contributors="7" :direct="5"
 *             :crowd="4.1" observer-name="alice"
 *             show-delta show-histogram
 *             :contributor-ratings="[4.5, 4.8, 4.2, 5, 4, 4.3, 4.7]"
 *             @aurora-click="openDrilldown" />
-->
<script setup>
import { onMounted, onBeforeUnmount, ref, computed, watch } from "vue";
import "@quidnug/web-components/src/primitives/index.js";

const props = defineProps({
    rating: { type: Number, default: null },
    max: { type: Number, default: 5 },
    crowd: { type: Number, default: null },
    contributors: { type: Number, default: 0 },
    direct: { type: Number, default: 0 },
    size: { type: String, default: "standard" },
    observerName: { type: String, default: "" },
    showValue: { type: Boolean, default: false },
    showDelta: { type: Boolean, default: false },
    showHistogram: { type: Boolean, default: false },
    contributorRatings: { type: Array, default: null },
});
const emit = defineEmits(["aurora-click"]);
const el = ref(null);

function handle(e) { emit("aurora-click", e.detail); }
onMounted(() => { el.value?.addEventListener("qn-aurora-click", handle); });
onBeforeUnmount(() => { el.value?.removeEventListener("qn-aurora-click", handle); });

const ratingsJson = computed(() =>
    props.contributorRatings ? JSON.stringify(props.contributorRatings) : null);
</script>

<template>
    <qn-aurora ref="el"
        :rating="rating != null ? String(rating) : null"
        :max="String(max)"
        :crowd="crowd != null ? String(crowd) : null"
        :contributors="String(contributors)"
        :direct="String(direct)"
        :size="size"
        :observer-name="observerName || null"
        :show-value="showValue ? '' : null"
        :show-delta="showDelta ? '' : null"
        :show-histogram="showHistogram ? '' : null"
        :contributor-ratings="ratingsJson"></qn-aurora>
</template>

// clients/react-reviews/src/primitives/QnAurora.jsx
import React from "react";
import "@quidnug/web-components/src/primitives/index.js";

/**
 * <QnAurora /> — React wrapper around the <qn-aurora> custom element.
 *
 * Props mirror the attributes of the primitive one-for-one, with
 * `contributorRatings` accepting a real JS array (we stringify it).
 * Events are surfaced as `onAuroraClick(detail)`.
 *
 * Use this when you already have rating + contributor state
 * computed (e.g. via `useTrustWeightedRating`) and just want to
 * render the glyph. For the full "fetch + compute + render"
 * experience see <QuidnugStars> or the upcoming <QuidnugRatingBadge>.
 */
export function QnAurora({
    rating,
    max = 5,
    crowd,
    contributors = 0,
    direct = 0,
    size = "standard",
    observerName,
    showValue,
    showDelta,
    showHistogram,
    contributorRatings,
    onAuroraClick,
    className,
    style,
    ...rest
}) {
    const ref = React.useRef(null);

    React.useEffect(() => {
        const el = ref.current;
        if (!el || !onAuroraClick) return;
        const handler = (e) => onAuroraClick(e.detail);
        el.addEventListener("qn-aurora-click", handler);
        return () => el.removeEventListener("qn-aurora-click", handler);
    }, [onAuroraClick]);

    const attrs = {
        ref,
        class: className,
        style,
        size,
        ...rest,
    };
    if (rating != null) attrs.rating = String(rating);
    attrs.max = String(max);
    if (crowd != null) attrs.crowd = String(crowd);
    attrs.contributors = String(contributors);
    attrs.direct = String(direct);
    if (observerName) attrs["observer-name"] = observerName;
    if (showValue) attrs["show-value"] = "";
    if (showDelta) attrs["show-delta"] = "";
    if (showHistogram) attrs["show-histogram"] = "";
    if (contributorRatings) {
        attrs["contributor-ratings"] = JSON.stringify(contributorRatings);
    }

    // React 19 passes unknown props through to custom elements as
    // attributes. On older React we fall back to a dangerouslySet
    // branch; this wrapper supports both by spreading attrs.
    return React.createElement("qn-aurora", attrs);
}
