// clients/vue-reviews/src/components/QuidnugStars.vue
<!--
 * <QuidnugStars product topic />
 *
 * Drop-in trust-weighted star rating for Vue apps. Requires
 * `provideQuidnug({ client, quid })` higher in the tree.
 *
 * Props mirror the React component one-for-one.
-->
<script setup>
import { computed, watch } from "vue";
import { useTrustWeightedRating } from "../composables/useTrustWeightedRating.js";

const props = defineProps({
    product: { type: String, required: true },
    topic: { type: String, required: true },
    max: { type: Number, default: 5 },
    showCount: { type: Boolean, default: false },
});
const emit = defineEmits(["rating"]);

const { data, loading, error } = useTrustWeightedRating(
    computed(() => props.product),
    computed(() => props.topic),
);

watch(data, (v) => { if (v) emit("rating", v); });

const rating = computed(() => data.value?.rating ?? null);

function starFill(i) {
    const v = rating.value;
    if (v == null) return 0;
    if (v >= i) return 1;
    if (v >= i - 0.5) return 0.5;
    return 0;
}

const stars = computed(() => {
    const out = [];
    for (let i = 1; i <= props.max; i++) out.push({ i, fill: starFill(i) });
    return out;
});

function gradId(i) {
    return `qng-half-${i}-${Math.random().toString(36).slice(2)}`;
}
</script>

<template>
    <span v-if="loading">…</span>
    <span v-else-if="error" :style="{ color: '#c0392b' }">⚠</span>
    <span v-else-if="rating == null"
          :style="{ color: '#888', fontStyle: 'italic' }">
        not enough trusted reviews
    </span>
    <span v-else
          :style="{ fontFamily: 'system-ui' }"
          :title="`${data.contributingReviews} of ${data.totalReviewsConsidered} contributed`">
        <span :style="{ display: 'inline-flex', gap: '2px' }">
            <svg v-for="s in stars" :key="s.i" width="18" height="18" viewBox="0 0 24 24">
                <template v-if="s.fill === 0">
                    <path fill="#e0e0e0"
                          d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
                </template>
                <template v-else-if="s.fill === 1">
                    <path fill="#F9A825"
                          d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
                </template>
                <template v-else>
                    <defs>
                        <linearGradient :id="gradId(s.i)">
                            <stop offset="50%" stop-color="#F9A825" />
                            <stop offset="50%" stop-color="#e0e0e0" />
                        </linearGradient>
                    </defs>
                    <path :fill="`url(#${gradId(s.i)})`"
                          d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
                </template>
            </svg>
        </span>
        <span :style="{ marginLeft: '6px', fontWeight: 600 }">{{ rating.toFixed(1) }}</span>
        <span :style="{ marginLeft: '4px', fontSize: '12px', color: '#666' }">
            ± {{ data.confidenceRange.toFixed(2) }}
        </span>
        <span v-if="showCount" :style="{ marginLeft: '4px', fontSize: '12px', color: '#666' }">
            ({{ data.contributingReviews }} trusted)
        </span>
    </span>
</template>

// clients/react-reviews/src/components/QuidnugStars.jsx
import React from "react";
import { useTrustWeightedRating } from "../hooks/useTrustWeightedRating.js";

/**
 * <QuidnugStars product="..." topic="..." />
 *
 * Drop-in trust-weighted star rating for React apps. Uses
 * <QuidnugProvider> higher in the tree.
 */
export function QuidnugStars({
    product,
    topic,
    max = 5,
    showCount = false,
    onRating,
    style,
    className,
}) {
    const { data, loading, error } = useTrustWeightedRating(product, topic);

    React.useEffect(() => {
        if (onRating && data) onRating(data);
    }, [data, onRating]);

    if (loading) return <span className={className} style={style}>…</span>;
    if (error) return <span style={{ color: "#c0392b", ...style }} className={className}>⚠</span>;

    const rating = data?.rating;
    if (rating == null) {
        return (
            <span className={className} style={{ color: "#888", fontStyle: "italic", ...style }}>
                not enough trusted reviews
            </span>
        );
    }

    return (
        <span className={className} style={{ fontFamily: "system-ui", ...style }}
              title={`${data.contributingReviews} of ${data.totalReviewsConsidered} contributed`}>
            <Stars value={rating} max={max} />
            <span style={{ marginLeft: 6, fontWeight: 600 }}>
                {rating.toFixed(1)}
            </span>
            <span style={{ marginLeft: 4, fontSize: 12, color: "#666" }}>
                ± {data.confidenceRange.toFixed(2)}
            </span>
            {showCount && (
                <span style={{ marginLeft: 4, fontSize: 12, color: "#666" }}>
                    ({data.contributingReviews} trusted)
                </span>
            )}
        </span>
    );
}

function Stars({ value, max }) {
    const items = [];
    for (let i = 1; i <= max; i++) {
        if (value >= i) {
            items.push(<Star key={i} fill={1} />);
        } else if (value >= i - 0.5) {
            items.push(<Star key={i} fill={0.5} />);
        } else {
            items.push(<Star key={i} fill={0} />);
        }
    }
    return <span style={{ display: "inline-flex", gap: 2 }}>{items}</span>;
}

function Star({ fill }) {
    const color = "#F9A825";
    const empty = "#e0e0e0";
    if (fill === 0) {
        return (
            <svg width="18" height="18" viewBox="0 0 24 24">
                <path fill={empty} d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
            </svg>
        );
    }
    if (fill === 1) {
        return (
            <svg width="18" height="18" viewBox="0 0 24 24">
                <path fill={color} d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
            </svg>
        );
    }
    // half
    const gradId = `qng-half-${Math.random().toString(36).slice(2)}`;
    return (
        <svg width="18" height="18" viewBox="0 0 24 24">
            <defs>
                <linearGradient id={gradId}>
                    <stop offset="50%" stopColor={color} />
                    <stop offset="50%" stopColor={empty} />
                </linearGradient>
            </defs>
            <path fill={`url(#${gradId})`}
                  d="M12 2l3 7 7 .6-5.3 4.7 1.7 7.2L12 17.8 5.6 21.5l1.7-7.2L2 9.6 9 9z" />
        </svg>
    );
}
