// clients/web-components/src/quidnug-review-list.js
import { getClient, getObserverQuid } from "./context.js";
import { Rater } from "./rater.js";

/**
 * <quidnug-review-list> — standalone list of reviews with per-review
 * trust-weights shown. Useful on review-aggregation pages or as a
 * second element next to <quidnug-review>.
 *
 * Attributes:
 *   product — required.
 *   topic   — required.
 *   limit   — max reviews to display (default 20).
 *   sort    — "weight" (default) | "recent" | "rating-high" | "rating-low"
 */
export class QuidnugReviewListElement extends HTMLElement {
    static get observedAttributes() { return ["product", "topic", "limit", "sort"]; }

    constructor() {
        super();
        this.attachShadow({ mode: "open" });
        this._result = null;
        this._reviews = [];
    }

    connectedCallback() {
        this._render();
        this._fetch();
    }

    attributeChangedCallback() {
        if (this.isConnected) {
            this._render();
            this._fetch();
        }
    }

    async _fetch() {
        const product = this.getAttribute("product");
        const topic = this.getAttribute("topic");
        if (!product || !topic) return;

        const client = getClient();
        if (!client) return;
        const observer = getObserverQuid()?.id ?? "anonymous";
        try {
            const rater = new Rater(client);
            this._result = await rater.effectiveRating(observer, product, topic);

            const streamRes = await client.getStreamEvents(product, {
                domain: topic,
                limit: Number(this.getAttribute("limit") ?? 20),
            });
            this._reviews = (streamRes.events ?? []).filter(e => e.eventType === "REVIEW");
            this._render();
        } catch { /* ignore */ }
    }

    _sorted() {
        const sort = this.getAttribute("sort") ?? "weight";
        const result = this._result;
        const weightMap = new Map(
            (result?.contributions ?? []).map(c => [c.reviewerQuid, c.weight])
        );
        const copy = [...this._reviews];
        switch (sort) {
            case "recent":
                copy.sort((a, b) => (b.timestamp ?? 0) - (a.timestamp ?? 0));
                break;
            case "rating-high":
                copy.sort((a, b) =>
                    (b.payload?.rating ?? 0) - (a.payload?.rating ?? 0));
                break;
            case "rating-low":
                copy.sort((a, b) =>
                    (a.payload?.rating ?? 0) - (b.payload?.rating ?? 0));
                break;
            case "weight":
            default:
                copy.sort((a, b) =>
                    (weightMap.get(b.creator) ?? 0) - (weightMap.get(a.creator) ?? 0));
        }
        return { sorted: copy, weightMap };
    }

    _render() {
        const { sorted, weightMap } = this._sorted();
        const rows = sorted.map((ev) => this._row(ev, weightMap.get(ev.creator))).join("");
        this.shadowRoot.innerHTML = `
            <style>${STYLES}</style>
            <div class="list">
                <div class="list-header">
                    <span>${this._reviews.length} reviews · sorted by ${this.getAttribute("sort") ?? "your-trust-weight"}</span>
                </div>
                ${rows || "<em class='empty'>no reviews</em>"}
            </div>
        `;
    }

    _row(ev, weight) {
        const p = ev.payload ?? {};
        const rating = p.rating ?? "?";
        const body = String(p.bodyMarkdown ?? "").slice(0, 280);
        const weightStr = weight != null ? weight.toFixed(2) : "—";
        const weightClass = weight != null && weight > 0.1 ? "ok" : "low";
        return `
            <div class="row">
                <div class="row-rating">★ ${rating}</div>
                <div class="row-body">
                    ${p.title ? `<strong>${escape(p.title)}</strong><br>` : ""}
                    ${escape(body)}
                </div>
                <div class="row-weight ${weightClass}" title="Your trust-weighted contribution">${weightStr}</div>
            </div>
        `;
    }
}

function escape(s) {
    return String(s ?? "").replace(/[&<>"']/g, (c) => ({
        "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
}

const STYLES = `
    :host {
        display: block;
        font-family: var(--quidnug-font, system-ui, sans-serif);
    }
    .list-header {
        font-size: 13px;
        color: #666;
        margin-bottom: 8px;
    }
    .row {
        display: grid;
        grid-template-columns: 60px 1fr 60px;
        gap: 12px;
        align-items: flex-start;
        padding: 10px;
        border-bottom: 1px solid #eee;
        font-size: 14px;
    }
    .row-rating {
        color: #F9A825;
        font-weight: 600;
    }
    .row-body strong {
        color: #0B1D3A;
    }
    .row-weight {
        font-family: monospace;
        font-size: 12px;
        text-align: right;
    }
    .row-weight.ok  { color: #2E8B57; }
    .row-weight.low { color: #aaa; }
    .empty { color: #888; }
`;

// clients/vue-reviews/src/components/QuidnugReviewList.vue
<script setup>
import { computed } from "vue";
import { useReviews } from "../composables/useReviews.js";

const props = defineProps({
    product: { type: String, required: true },
    topic: { type: String, required: true },
    contributions: { type: Array, default: () => null },
    sort: { type: String, default: "weight" },
    limit: { type: Number, default: 20 },
});

const { data: reviews, loading, error } = useReviews(
    () => props.product,
    () => props.topic,
    { limit: props.limit },
);

const weightMap = computed(() => {
    if (!props.contributions) return new Map();
    return new Map(props.contributions.map((c) => [c.reviewerQuid, c.weight]));
});

const sorted = computed(() => {
    const copy = [...reviews.value];
    const m = weightMap.value;
    const byWeight = (a, b) => (m.get(b.creator) ?? 0) - (m.get(a.creator) ?? 0);
    const byRecent = (a, b) => (b.timestamp ?? 0) - (a.timestamp ?? 0);
    const byHigh = (a, b) => (b.payload?.rating ?? 0) - (a.payload?.rating ?? 0);
    const byLow = (a, b) => (a.payload?.rating ?? 0) - (b.payload?.rating ?? 0);
    switch (props.sort) {
        case "recent": copy.sort(byRecent); break;
        case "rating-high": copy.sort(byHigh); break;
        case "rating-low": copy.sort(byLow); break;
        case "weight":
        default: copy.sort(byWeight);
    }
    return copy;
});

function weightFor(ev) { return weightMap.value.get(ev.creator); }
function isContributing(w) { return w != null && w > 0.1; }
</script>

<template>
    <div v-if="loading" style="color:#888">Loading reviews…</div>
    <div v-else-if="error" style="color:#c0392b">
        {{ error.message || String(error) }}
    </div>
    <em v-else-if="sorted.length === 0" style="color:#888">No reviews yet</em>
    <div v-else style="display:flex;flex-direction:column;gap:12px;margin-top:12px">
        <div v-for="ev in sorted"
             :key="`${ev.subjectId}-${ev.sequence}`"
             :style="{
                 padding: '10px 12px',
                 borderRadius: '6px',
                 background: '#f7f7f7',
                 borderLeft: `3px solid ${isContributing(weightFor(ev)) ? '#2E8B57' : '#ccc'}`,
                 opacity: isContributing(weightFor(ev)) ? 1 : 0.55,
                 fontSize: '14px',
             }">
            <div style="display:flex;gap:8px;align-items:center">
                <span style="color:#F9A825;font-weight:600">★ {{ ev.payload?.rating }}</span>
                <strong v-if="ev.payload?.title">{{ ev.payload.title }}</strong>
                <span :style="{
                          fontSize: '11px',
                          color: isContributing(weightFor(ev)) ? '#2E8B57' : '#999',
                          fontFamily: 'monospace',
                      }">
                    {{ weightFor(ev) != null
                        ? `weight ${weightFor(ev).toFixed(2)}`
                        : 'outside your trust' }}
                </span>
            </div>
            <div style="font-family:monospace;font-size:11px;color:#888;margin:4px 0">
                by {{ String(ev.creator ?? '').slice(0, 10) }}…
            </div>
            <div>{{ ev.payload?.bodyMarkdown }}</div>
        </div>
    </div>
</template>
